# Generated by Django 4.0.4 on 2022-05-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [{'custom person permission', 'custom_person_permission'}]},
        ),
    ]
